import 'package:flutter/material.dart';
import 'hexColor.dart';

var primary = HexColor('#f1f1e8');
var secondary = HexColor('707070');
var green2 = HexColor('206a5d');
var green1 = HexColor('81b214');
var green3 = HexColor('bfdcae');
var accent = HexColor('FDD619');
var buttondisabled = HexColor('cccccc');
var buttonenabled = HexColor('FDD619');
var black2 = HexColor('222222');
var white = Colors.white;
var black = Colors.black;
var gray = HexColor('aaaaaa');
var grey = HexColor('aaaaaa');
var gray2 = HexColor('6b6b6b');
var grey2 = HexColor('6b6b6b');
var yellow = HexColor('FDD619');
var gray3 = HexColor("eeeeee");
var grey3 = HexColor("eeeeee");
var red = Colors.red;
var textred = Colors.red;
var textwhite = Colors.white;
var textblack = Colors.black;
var textgrey = Colors.grey;
var blue = Colors.blue;
var blueAccent = Colors.blueAccent;
